export const mockChatsList = [
  {
    name: 'Иванов Иван Иванович',
    id: 'ID 112230',
    avatar: '1',
    message: 'Да, я понял, так и сделаю, завтра отчитаюсь',
    notifications: 5,
  },
  {
    name: 'Чебурашка Карина Игоревна',
    id: 'ID 112231',
    avatar: '1',
    message: 'Волонтер не пришел в назначенное время',
    notifications: 3,
  },
  {
    name: 'Игошина Яна Витальевна',
    id: 'ID 112232',
    avatar: '1',
    message: 'Договорились, так и сделаем',
    notifications: 0,
  },
  {
    name: 'Курицин Ян Олегович',
    id: 'ID 112233',
    avatar: '1',
    message: 'Договорились, так и сделаем',
    notifications: 0,
  },
  {
    name: 'Иванов Иван Иванович',
    id: 'ID 112234',
    avatar: '1',
    message: 'Договорились, так и сделаем',
    notifications: 0,
  },
  {
    name: 'Иванов Иван Иванович',
    id: 'ID 112235',
    avatar: '1',
    message: 'Договорились, так и сделаем',
    notifications: 0,
  },
  {
    name: 'Иванов Иван Иванович',
    id: ' ID 112236',
    avatar: '1',
    message: 'Договорились, так и сделаем',
    notifications: 0,
  },
  {
    name: 'Иванов Иван Иванович',
    id: 'ID 112237',
    avatar: '1',
    message: 'Договорились, так и сделаем',
    notifications: 0,
  },
  {
    name: 'Иванов Иван Иванович',
    id: 'ID 112238',
    avatar: '1',
    message: 'Договорились, так и сделаем',
    notifications: 0,
  },
  {
    name: 'Иванов Иван Иванович',
    id: 'ID 112239',
    avatar: '1',
    message: 'Договорились, так и сделаем',
    notifications: 0,
  },
  {
    name: 'Иванов Иван Иванович',
    id: 'ID 112240',
    avatar: '1',
    message: 'Договорились, так и сделаем',
    notifications: 0,
  },
];
