export const testUsers: any = [
  {
    role: 'volunteer',
    avatarName: 'Volunteer Avatar',
    userName: 'VИванов Иван Иванович',
    userId: 123,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: true,
      checked: true,
      keys: true,
      adminStatus: null,
      scores: 60,
    },
  },
  {
    role: 'recipient',
    avatarName: 'Volunteer Avatar',
    userName: 'RСеменов Петр Игоревич',
    userId: 124,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: true,
      checked: false,
      keys: true,
      adminStatus: null,
      scores: 60,
    },
  },

  {
    role: 'volunteer',
    avatarName: 'Volunteer Avatar',
    userName: 'VИванов Иван Иванович',
    userId: 125,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: false,
      checked: false,
      keys: false,
      adminStatus: null,
      scores: 0,
    },
  },
  {
    role: 'recipient',
    avatarName: 'Volunteer Avatar',
    userName: 'RИванов Иван Иванович',
    userId: 126,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: false,
      checked: false,
      keys: false,
      adminStatus: null,
      scores: 0,
    },
  },
  {
    role: 'admin',
    avatarName: 'Volunteer Avatar',
    userName: 'AИванов Иван Иванович',
    userId: 127,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: false,
      checked: false,
      keys: false,
      adminStatus: null,
      scores: 40,
    },
  },
  {
    role: 'admin',
    avatarName: 'Volunteer Avatar',
    userName: 'AИванов Иван Иванович',
    userId: 128,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: true,
      checked: false,
      keys: false,
      adminStatus: null,
      scores: 40,
    },
  },
  {
    role: 'admin',
    avatarName: 'Volunteer Avatar',
    userName: 'AИванов Иван Иванович',
    userId: 129,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: true,
      checked: false,
      keys: false,
      adminStatus: null,
      scores: 40,
    },
  },
  {
    role: 'admin',
    avatarName: 'Volunteer Avatar',
    userName: 'AИванов Иван Иванович',
    userId: 130,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: true,
      checked: false,
      keys: false,
      adminStatus: null,
      scores: 40,
    },
  },
  {
    role: 'volunteer',
    avatarName: 'Volunteer Avatar',
    userName: 'VИванов Иван Иванович',
    userId: 131,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: false,
      checked: false,
      keys: false,
      adminStatus: null,
      scores: 0,
    },
  },
  {
    role: 'recipient',
    avatarName: 'Volunteer Avatar',
    userName: 'RИванов Иван Иванович',
    userId: 132,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: false,
      checked: false,
      keys: false,
      adminStatus: null,
      scores: 0,
    },
  },

  {
    role: 'volunteer',
    avatarName: 'Volunteer Avatar',
    userName: 'VИванов Иван Иванович',
    userId: 133,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: false,
      checked: false,
      keys: false,
      adminStatus: null,
      scores: 0,
    },
  },
  {
    role: 'recipient',
    avatarName: 'Volunteer Avatar',
    userName: 'RИванов Иван Иванович',
    userId: 134,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: false,
      checked: false,
      keys: false,
      adminStatus: null,
      scores: 0,
    },
  },

  {
    role: 'volunteer',
    avatarName: 'Volunteer Avatar',
    userName: 'VИванов Иван Иванович',
    userId: 135,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: false,
      checked: false,
      keys: false,
      adminStatus: null,
      scores: 0,
    },
  },
  {
    role: 'recipient',
    avatarName: 'Volunteer Avatar',
    userName: 'RИванов Иван Иванович',
    userId: 136,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: false,
      checked: false,
      keys: false,
      adminStatus: null,
      scores: 0,
    },
  },
  {
    role: 'admin',
    avatarName: 'Volunteer Avatar',
    userName: 'AИванов Иван Иванович',
    userId: 137,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: true,
      checked: false,
      keys: false,
      adminStatus: null,
      scores: 40,
    },
  },
  {
    role: 'volunteer',
    avatarName: 'Volunteer Avatar',
    userName: 'VИванов Иван Иванович',
    userId: 138,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: true,
      checked: false,
      keys: false,
      adminStatus: null,
      scores: 0,
    },
  },
  {
    role: 'recipient',
    avatarName: 'Volunteer Avatar',
    userName: 'RИванов Иван Иванович',
    userId: 139,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: true,
      checked: false,
      keys: false,
      adminStatus: null,
      scores: 0,
    },
  },
  {
    role: 'admin',
    avatarName: 'Volunteer Avatar',
    userName: 'AИванов Иван Иванович',
    userId: 140,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: true,
      checked: false,
      keys: false,
      adminStatus: null,
      scores: 40,
    },
  },
];
