import { UserRole } from 'shared/types/common.types';

export const testUsers: any = [
  {
    role: 'volunteer',
    avatarName: 'Volunteer Avatar',
    userName: 'Иванов Иван Иванович',
    userId: 12345,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: true,
      checked: true,
      keys: true,
      adminStatus: null,
      scores: 60,
    },
  },
  {
    role: UserRole.RECIPIENT,
    avatarName: 'Volunteer Avatar',
    userName: 'Семенов Петр Игоревич',
    userId: 12345,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: true,
      checked: false,
      keys: true,
      adminStatus: null,
      scores: 60,
    },
  },

  {
    role: 'volunteer',
    avatarName: 'Volunteer Avatar',
    userName: 'Иванов Иван Иванович',
    userId: 12345,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: false,
      checked: false,
      keys: false,
      adminStatus: null,
      scores: 0,
    },
  },
  {
    role: UserRole.RECIPIENT,
    avatarName: 'Volunteer Avatar',
    userName: 'Иванов Иван Иванович',
    userId: 12345,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: false,
      checked: false,
      keys: false,
      adminStatus: null,
      scores: 0,
    },
  },
  {
    role: UserRole.ADMIN,
    avatarName: 'Volunteer Avatar',
    userName: 'Иванов Иван Иванович',
    userId: 12345,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: true,
      checked: false,
      keys: false,
      adminStatus: null,
      scores: 40,
    },
  },
  {
    role: UserRole.ADMIN,
    avatarName: 'Volunteer Avatar',
    userName: 'Иванов Иван Иванович',
    userId: 12345,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: true,
      checked: false,
      keys: false,
      adminStatus: null,
      scores: 40,
    },
  },
  {
    role: UserRole.ADMIN,
    avatarName: 'Volunteer Avatar',
    userName: 'Иванов Иван Иванович',
    userId: 12345,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: true,
      checked: false,
      keys: false,
      adminStatus: null,
      scores: 40,
    },
  },
  {
    role: UserRole.ADMIN,
    avatarName: 'Volunteer Avatar',
    userName: 'Иванов Иван Иванович',
    userId: 12345,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: true,
      checked: false,
      keys: false,
      adminStatus: null,
      scores: 40,
    },
  },
  {
    role: 'volunteer',
    avatarName: 'Volunteer Avatar',
    userName: 'Иванов Иван Иванович',
    userId: 12345,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: false,
      checked: false,
      keys: false,
      adminStatus: null,
      scores: 0,
    },
  },
  {
    role: UserRole.RECIPIENT,
    avatarName: 'Volunteer Avatar',
    userName: 'Иванов Иван Иванович',
    userId: 12345,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: false,
      checked: false,
      keys: false,
      adminStatus: null,
      scores: 0,
    },
  },

  {
    role: 'volunteer',
    avatarName: 'Volunteer Avatar',
    userName: 'Иванов Иван Иванович',
    userId: 12345,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: false,
      checked: false,
      keys: false,
      adminStatus: null,
      scores: 0,
    },
  },
  {
    role: UserRole.RECIPIENT,
    avatarName: 'Volunteer Avatar',
    userName: 'Иванов Иван Иванович',
    userId: 12345,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: false,
      checked: false,
      keys: false,
      adminStatus: null,
      scores: 0,
    },
  },

  {
    role: 'volunteer',
    avatarName: 'Volunteer Avatar',
    userName: 'Иванов Иван Иванович',
    userId: 12345,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: false,
      checked: false,
      keys: false,
      adminStatus: null,
      scores: 0,
    },
  },
  {
    role: UserRole.RECIPIENT,
    avatarName: 'Volunteer Avatar',
    userName: 'Иванов Иван Иванович',
    userId: 12345,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: false,
      checked: false,
      keys: false,
      adminStatus: null,
      scores: 0,
    },
  },
  {
    role: UserRole.ADMIN,
    avatarName: 'Volunteer Avatar',
    userName: 'Иванов Иван Иванович',
    userId: 12345,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: true,
      checked: false,
      keys: false,
      adminStatus: null,
      scores: 40,
    },
  },
  {
    role: 'volunteer',
    avatarName: 'Volunteer Avatar',
    userName: 'Иванов Иван Иванович',
    userId: 12345,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: false,
      checked: false,
      keys: false,
      adminStatus: null,
      scores: 0,
    },
  },
  {
    role: UserRole.RECIPIENT,
    avatarName: 'Volunteer Avatar',
    userName: 'Иванов Иван Иванович',
    userId: 12345,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: false,
      checked: false,
      keys: false,
      adminStatus: null,
      scores: 0,
    },
  },
  {
    role: UserRole.ADMIN,
    avatarName: 'Volunteer Avatar',
    userName: 'Иванов Иван Иванович',
    userId: 12345,
    userNumber: '+1 (123) 456-7890',
    avatarLink: 'https://i.pravatar.cc/300',
    volunteerInfo: {
      approved: true,
      checked: false,
      keys: false,
      adminStatus: null,
      scores: 40,
    },
  },
];
