export const FilterItemsIds = {
  ALL: 'all',
  VOLUNTEER: 'volunteer',
  RECIPIENT: 'recipient',
  UNHANDLED: 'unhandled',
  CATEGORY_1: '1',
  CATEGORY_2: '2',
  CATEGORY_3: '3',
  CATEGORY_4: '4',
  CATEGORY_5: '5',
  CATEGORY_6: '6',
  RADIUS_1: '1',
  RADIUS_3: '3',
  RADIUS_5: '5',
  SHOW_BY_DATE: 'showByDate',
};
